### PR TITLE
fiber coupling software

### PR DESCRIPTION
**Pull request by mkbhaskar**
Created a software interface using power-monitoring for fiber-coupling. Includes
- Driver for thorlabs PM320E dual-channel power-meter (using IEEE interface, connected over USB). See `pylabnet.hardware.power_meter.thorlabs_pm320e` module
- GUI for monitoring input, reflection, and coupling efficiency graphs + current values (no steps taken yet to optimize aesthetics...)
- Launchers for convenient launching of the full software

**__NOTE 1__:** The calibration value is currently stored in the `pylabnet.scripts.fiber_coupling.power_monitor` module as a constant attribute `CALIBRATION` of the `Monitor` class

**__NOTE 2__:** If you want to use the launch control launching, you need to have the GPIB address set in the `pylabnet.launchers.servers.thorlabs_pm320e.py` module

### CODE REVIEW

**Comment by cknaut** [comment]
Looks good. Only issue I had was that the current power values are too small to be displayed. I added a automatic prefix formatting routine, which should decomposes for example 1e-9 in (1, 'n'). If you think this is useful, the prefix information still needs to be  displayed somewhere (for example in a label after the actual number).

**Comment by mkbhaskar** [comment]
Added the prefixes as well as ability to set wavelength and power ranges (it works within reason, but the ranges allowed depends on the sensor plugged in, so one should be a bit careful in practice)

Maybe have a look @cknaut?

**Comment by cknaut** [comment]
Checked it out and noticed that if the input signal is too high for a selected range, the GUI freezes (probably because the `get_power` returns some `NaN`). The range change seems to work for some ranges, which probably depend on the sensor, as you pointed out.

**Comment by mkbhaskar** [comment]
> the GUI freezes (probably because the get_power returns some NaN). 

@cknaut This issue is solved in 8848ec3. I also changed the software to default to AUTO range upon initialization since the software would crash on startup in a way that depended on the previous range settings of the device. Now it seems to work properly

**Pull request merged**
