### PR TITLE
server closing - eliminating consoles

### PR DESCRIPTION
**Pull request by mkbhaskar**
- Changed all launching to hide consoles completely (they run as background tasks, and only appear when needed for user input). 
- Added functionality to `GenericServer`, `ServiceBase`, and `ClientBase` to allow for closing of servers and server threads.
    - `GenericServer.stop()` will stop the server so that the thread in which it is running can continue (and terminate on its own, if applicable)
    - `ServiceBase.close_server()` will kill the thread associated with this service, thereby closing any running servers
    - `ClientBase.close_server()` will invoke `client._service.close_server()`, allowing one to  create a client to connect to a running server and close it. **In principle, this poses a security hazard, but it is very convenient, since otherwise the only way to close these threads is to have a physical console, or to kill them from task manager**
- Now, one can close threads not via closing the python console, but directly via `Launch Control`. One can highlight the thread to be closed, and click the red `Close server` button
image
- This connects a `ClientBase` to the `GenericServer` running in the higlighted thread, and calls `ClientBase.close_server()`, resulting in termination of that thread
image
- Improved GUI functionality so that hitting the `X` button of the GUI depresses the `stop_button` attribute, and gracefully exits the running thread + closes any GUI server. **Previously, one could close the GUI, but the python process would hang around.** Note there should *always* be a checkable `AbstractButton` named `stop_button` in the .ui file for the GUI to work properly
- Modified `Launch Control` so that when it is closed, it closes all running servers attached to it. This could possibly be a vulnerability, but I am not sure we want to use servers running in their own console without being attached to the centralized logger. However, this may be something we can consider removing - @cknaut  we should consider carefully

### CODE REVIEW

**Comment by cknaut** [comment]
I agree, the `ClientBase.close_server()` can potentially pose security hazards, especially in a future scenario where some ports will be opened to the internet. Maybe we can explore ways to use classical connection authentication in order to prevent a third party connecting to and killing our servers. `rpyc` seems to have some built-in capabilities: https://rpyc.readthedocs.io/en/latest/api/utils_authenticators.html

**Comment by mkbhaskar** [comment]
@cknaut please see the implementation of `pylabnet.network.core.generic_server.SecureServer` and `pylabnet.network.core.client_base.SecureClient`, which uses a private SSL key named `pylabnet.pem` placed in the `Windows/System32` directory (this is a 1024 bit RSA key). The functionality is demonstrated in the `pylabnet.demo.server_testing.ipynb` notebook

The idea would be to copy this authentication file onto trusted computers, so that only they could attach to pylabnet servers. One day, we could even generate this key using quantum key distribution ;)

**Comment by mkbhaskar** [comment]
@cknaut can you check this again? I made substantial changes such that the package now defaults to running with a key titled `pylabnet.pem` in the `C:/Windows/System32` directory. 

The package can be run "insecurely" by launching servers and clients manually (e.g. from a notebook or shell) with the `key=None` kwarg.

**Comment by cknaut** [comment]
Looks good. I did test this out in a notebook and it worked. Only observation: If no key is present in the  `C:/Windows/System32` folder, it is possible to start a `SecureServer`, and only if one tries to connect to it it will throw an error. I would have expected an error earlier, e.g. at the moment of the instantiation of the `SecureServer`. As I understand it,  the timing of this error does not impact the security of the server (at no point an unsecured connection is assumed to be secure), so I'm fine with leaving it as is and only implementing a manual error message if it proves to be useful. 

Good luck with the manual merge :)

**Comment by mkbhaskar** [comment]
> If no key is present in the C:/Windows/System32 folder, it is possible to start a SecureServer

Good point - this is fixed with fe0e2b6, which checks that the keyfile exists before starting a secure server.

**Pull request merged**
