### PR TITLE
Kasa smartplug integration

### PR DESCRIPTION
**Pull request by cknaut**
Using a local LAN and wifi, we can now easily use commercial wifi-based smart home devices. This is a driver + staticline driver for the [TP-Link Kasa H103](https://www.bhphotovideo.com/c/product/1558624-REG/tp_link_hs103_wi_fi_smart_plug.html), for which there exists a neat [python API](https://python-kasa.readthedocs.io/en/latest/cli.html). 

The plugs are configured using the Kasa app (iOS or Android). Just follow the instructions and connect the plug to the `pylabnet` wifi. After the plugs are connected to the `pylabnet` wifi, the Kasa app can be used to change the aliases of the plugs (make sure to switch to the `pylabnet` wifi on the app-device before this step). The plugs can be assigned subsequent generic names and properly labeled. A config file `smart_plug_config` then matches the generic names to a human readable plug location:

```
{
    "HS103": [
        {
            "alias": "HS103_SMART_PLUG_01",
            "device_id": "Powermeter Front Smart Plug"
        },
        {
            "alias": "HS103_SMART_PLUG_02",
            "device_id": "Fridge LEDs Smart Plug"
        }
    ]
}
```

Now, the  smart plugs can easily be addressed as follows:

```python
from pylabnet.hardware.smart_lab.smart_plug.tp_link_hs103 import Driver

smart_plug = Driver(
        logger=logger
)

smart_plug.turn_on("Powermeter Front Smart Plug")

```

This PR includes a staticline driver which enables the use of the staticline GUI to control the smart plugs:
image

### CODE REVIEW

**Review by pieterjanstas — APPROVED** [review]
All looks good!

**Comment by danielra97** [comment]
I'm a bit confused how device_id is used here. So you instantiate a single driver for the tp_link_hs103  object and index separate plugs within the driver using multiple device ids assigned to each individual plug, passing them in as a parameter to function calls? Do you also give the whole tp_link_hs103 object a device_id for pylabnet device server lookup purposes? If I'm understanding it right, wouldn't it be cleaner to use device_id as a member variable of the driver and we instantiated a separate driver for each individual plugs (though I'm guessing you had a reason for not doing it that way). However, given that this isn't the most vital code in the world it's probably fine if we want to let it slide.

**Comment by cknaut** [comment]
Yep, initially implemented it the way you suggested. Switched to only instantiating one driver object due to two reasons:

1. The `Discover` function used to find and instantiate one smart plug also provides access to all smart plugs on the network. To reinstantiate a second driver would thus create unnecessary overhead.

2. From a conceptual level, I think it is fair to think of multiple smart plugs as different "channels" of one (distributed) device. This way all smart plugs also organically show up in one subsection of the staticline GUI.

**Comment by danielra97** [comment]
Made changes to format so now the list of channels is contained within teh device's config file and we call them channel_id as opposed to device_id to avoid any confusion there. Ready to merge.

**Review by danielra97 — APPROVED** [review]
Good to go after changes mentioned above

**Pull request merged**
