### PR TITLE
Slackbot integration to logger

### PR DESCRIPTION
**Pull request by cknaut**
This PR integrates the Slack API into pylabnet. Usage is as follows:

1. Subscribe to a channel by adding the following config file:

`slackbot.json`

```json
{
    "logger_channel": "#pylabnet_slackbot"
}
```

The logger channel is the channel where every slackbot message will be posted. It will make sense to have one for every lab.

2. Add the Slackbot access token to the `.env` file (ask me).
3. Post to channel via logging command:

```python
value = 5
CRITICAL_VALUE = 2

if value > CRITICAL_VALUE:
    logger.slack('Critical Value Exceeded')
```

image

Usage of this functionality is mainly for remote experiments and to alert if parameters are out of spec / or push periodic updates, not for general debugging purpose.

### CODE REVIEW

**Comment by pieterjanstas** [comment]
Very cool! Looks good to me

A few questions I have are: 
- Does the channel need to be created on slack before instantiating the slackbot on a certain channel name? And what happens if the channel does not exist yet? Does a new channel get created or does it throw an error?
- Can the slackbot handle multiple programs running at the same time sending commands?
- We should create a fun icon for the slackbot.

**Comment by cknaut** [comment]
> Does the channel need to be created on slack before instantiating the slackbot on a certain channel name? And what happens if the channel does not exist yet? Does a new channel get created or does it throw an error?

Good question. Right now, it probably throws a badly handled error. Will fix this to output a proper error to the logger. In general,  I think it should not auto-create a slack channel, in order to avoid overcrowding the Slack. 

> Can the slackbot handle multiple programs running at the same time sending commands?

It is implemented on the level of the master logger, so it should be able to handle that. 

> We should create a fun icon for the slackbot.

Absolutely. Here are the size restrictions, if you want to give it a go: 

`Icons must be squares between 512px by 512px and 2000px by 2000px`

**Review by danielra97 — APPROVED** [review]
Looks good. Only possible feature would be being able to post to different channels from a single pylabnet instance, but like we discussed might not be desired since we want to use this feature sparingly.

**Review by pieterjanstas — APPROVED** [review]

**Comment by pieterjanstas** [comment]
I'll try coming up with a cool icon idea!

**Pull request merged**
