### PR TITLE
Fixed partial requisite server loading issue #238

### PR DESCRIPTION
**Pull request by danielra97**
For issue #238, implemented general ability for scripts to load with only some of their requisite servers instantiated, and implemented this ability in the datataker and staticlines scripts.

The general workflow is now `launch_controller.py` is setup so that it will not crash if not all the requisite servers are instantiated when a new server is launched provided that the '"optional_clients"' parameter is set as '"True"' in the new server's config file . The new script server can then determine whether their requisite client servers have been instantiated by using the same 'find_client' function as before, but checking if 'find_client' returns 'None'. It is up to the new script server to figure out how they want to handle missing a requisite server. This may not be as general as originally desired, but it seems like the best way given that we don't necessarily have a general way we want the servers to behave in that instance. 

In the case of staticlines, missing requisite device servers will just cause the region of the GUI corresponding with that device's control to not appear. In the case of datataker, the name of the missing device servers will still be displayed on the list on the right hand side of the GUI, but they will be greyed out. 

In addition to this, a new parameter for config files, '"num_connect_tries"' has been implemented. This corresponds with  the number of times a new server will try to connect to a newly instantiated requisite server before giving up and continuing on without the requisite server. If this number is not specified in the config file, a default of 10 will be assumed.

### CODE REVIEW

**Comment by cknaut** [comment]
Nice! A couple of questions:

- Does the 1D scanner also has the greyed out feature enabled? Should be analogous to the data-taker. 
- Does the data-taker throw a smart error if an experiment is launched with a greyed-out server a requisite?
- Does the data-taker check again before loading an experiment if one of the previously greyed out servers has connected in the meantime?

**Comment by danielra97** [comment]
We can, but the end result is the same, nothing happens

**Comment by danielra97** [comment]
For 1D scanner I did not implement because of how 1D scanner handles adding its clients, but its pretty straightforward to add so I can do that quickly.  

For the data-taker checking, is there any property in already existing experiment scripts specifying their required clients? If not we will need to add that. We can of course do that, we just should be sure we are all on board with that, could have some backwards compatibility issues (though we can probably get around it). 

For the third point, no its only when starting the datataker. Having clients able to connect after the datataker has been initialized will require a more serious overhaul I think (its pretty different from how we currently pass client data to new servers which is via the command line upon instantiation).

**Comment by cknaut** [comment]
> For 1D scanner I did not implement because of how 1D scanner handles adding its clients, but its pretty straightforward to add so I can do that quickly.

Cool, I think it would be useful!

> For the data-taker checking, is there any property in already existing experiment scripts specifying their required clients? If not we will need to add that. We can of course do that, we just should be sure we are all on board with that, could have some backwards compatibility issues (though we can probably get around it).

I would suggest solving this by replacing this

```python
 ai_nidaq : nidaqmx_card.Client = kwargs['nidaqmx_daq_ai']
```

by something like

```python
nidaqmx_card.Client = retrieve_client('nidaqmx_daq_ai')
```

where `retrieve_client()` then checks if the servers are greyed out. 

> For the third point, no its only when starting the datataker. Having clients able to connect after the datataker has been initialized will require a more serious overhaul I think (its pretty different from how we currently pass client data to new servers which is via the command line upon instantiation).

Ok fair, let's pass on it then.

**Pull request merged**
