### PR TITLE
packaging

### PR DESCRIPTION
**Pull request by mkbhaskar**
Modified the package to be pip installable. See `pylabnet/README.md` for the full documentation. At a high level, one can now simply run `pip install pylabnet` and have access to `import pylabnet` statements from arbitrary scripts or IPython sessions without cloning repositories, modifying path variables, or any other shenangians. Furthermore, the `pip install pylabnet` creates executables `pylabnet.exe` and `pylabnet_proxy.exe` which perform the basic launching functionality.

At a more technical level, the magic is contained in `pylabnet/setup.py`. By running the command
```bash
python setup.py sdist bdist_wheel
```
one builds a distributable that can subsequently be uploaded to pip (with proper credentials) using
```bash
twine upload dist/*
```
`setup.py` contains all relevant information about the package. This includes the addition of a license and a version numbering scheme (the version is stored in `pylabnet.__init__.py`).

Additionally, I have depreciated explicit support for dedicated conda environments in support of pip virtual environments. This has been tested to work and is documented `pylabnet/README.md`. The advantage of this is to prevent the necessity for modification of PYTHONPATH variables to manually include the pylabnet module directory. It should also prevent conflicts with other python packages (for example, the latest version of spyder).

Recommended test strategy for *users*:
1. Create pip virtual environment
```bash
python -m venv /path/to/new/virtual/testenv
```
2. Activate environment
```bash
/path/to/new/virtual/testenv/Scripts/activate
```
3. Run the command `pip install pylabnet`
4. Test `pylabnet.exe` and `pylabnet_proxy.exe` (should be able to find them from windows start/search

Recommended test strategy for *developers*:
1. Create a **new** pip virtual environment
```bash
python -m venv /path/to/another/new/virtual/testenv
```
2. Activate environment
```bash
/path/to/another/new/virtual/testenv/Scripts/activate
```
3. Go to root pylabnet directory and run 
```bash
python setup.py develop --exclude-scripts /path/to/another/new/virtual/testenv/Scripts/activate
```
4. Test basic functionality
5. If desired, make changes and try uploading a new version to pip (e.g. v0.2.6)
    - Make changes to repository
    - Change version number in `pylabnet/__init__.py`
    - Add updates to `CHANGELOG.md`
    - commit/push
    - Create a git tag for v0.2.6 for latest commit
    - From root directory run (with environment activated) `python setup.py sdist bdist_wheel` (requires `pip install wheel`)
    - Run `twine upload dist/*` (make sure you have pip credentials)

### CODE REVIEW

**Comment by cknaut** [comment]
I have tested this branch as follows:

## `pip` install

1. Created a virtual environement using `python -m venv env`, activated it and run `pip install pylabnet` in it.

2. Removed all paths to pylabnet in the environement variables, renamed my local pylabnet folders such that the `import pylabnet` command fails outside the virtual environement. 

2. Did run `jupyter notebook` in activated terminal, and tested a HDAWG tutorial. The folder name got changed from zi_hdawg to ZI_HDAWG, but after adjusting this it worked great.


 > **_NOTE:_**  We can think about 'registering' some functions or classes in the `__init__.py` file, which would allow us to access them directly without specifying the path. For instance, adding `from .network.core.generic_server import GenericServer` to the `__init__.py` should make it possible to import `GenericServer` as follows: `from pylabnet import GenericServer`. Maybe this could even circumvent our duplicated `Driver()` designations. If we could rename the `Driver()` classes in the `__init__.py`, and if this renaming would not cause problems in the new launcher workflow, we'd be in business.

Will check the developer workflow next.

**Comment by cknaut** [comment]
I have tried to search for `pylabnet.exe` and `pylabnet_proxy.exe`, but could not find them. My `PATH` variable also doesn't show any reference to these two files.

**Comment by mkbhaskar** [comment]
> I have tried to search for `pylabnet.exe` and `pylabnet_proxy.exe`, but could not find them. My `PATH` variable also doesn't show any reference to these two files. 

Should only exist for vanilla `pip install pylabnet` but not `python setup.py develop --exclude-scripts`. I can change this, but one thing that's a bit untidy is that for some reason the .exe is not removed when you use `pip uninstall pylabnet` for developer mode

**Comment by cknaut** [comment]
> > I have tried to search for `pylabnet.exe` and `pylabnet_proxy.exe`, but could not find them. My `PATH` variable also doesn't show any reference to these two files.
> 
> Should only exist for vanilla `pip install pylabnet` but not `python setup.py develop --exclude-scripts`. I can change this, but one thing that's a bit untidy is that for some reason the .exe is not removed when you use `pip uninstall pylabnet` for developer mode

I've only checked it for the `pip install pylabnet` and couldn't find it.

**Comment by mkbhaskar** [comment]
> I have tested this branch as follows:

## `pip` install

1. Created a virtual environement using `python -m venv env`, activated it and run `pip install pylabnet` in it.

2. Removed all paths to pylabnet in the environement variables, renamed my local pylabnet folders such that the `import pylabnet` command fails outside the virtual environement. 

2. Did run `jupyter notebook` in activated terminal, and tested a HDAWG tutorial. The folder name got changed from zi_hdawg to ZI_HDAWG, but after adjusting this it worked great.


 > **_NOTE:_**  We can think about 'registering' some functions or classes in the `__init__.py` file, which would allow us to access them directly without specifying the path. For instance, adding `from .network.core.generic_server import GenericServer` to the `__init__.py` should make it possible to import `GenericServer` as follows: `from pylabnet import GenericServer`. Maybe this could even circumvent our duplicated `Driver()` designations. If we could rename the `Driver()` classes in the `__init__.py`, and if this renaming would not cause problems in the new launcher workflow, we'd be in business.

Will check the developer workflow  and `pylabnet.exe` next.
 

sounds like an interesting note, I'm open to it especially for widely used core functionality like `GenericServer` but I'm not really sure how this solves issues with `Driver()` naming

**Comment by cknaut** [comment]
I have tried to replicate the test strategy for developers:

1. Make new env, activate env, run `python setup.py develop --exclude-scripts /path/to/another/new/virtual/testenv/Scripts/activate`

Now, if I run `import pylabnet` from the root directory of the pylabnet folder, it works, but trying to import `pylabnet` from any other location, say from one of the demo notebooks, the import fails. This is how my `pip list` entry for `pylabnet` looks like:
image
 
`

**Comment by mkbhaskar** [comment]
> > > I have tried to search for `pylabnet.exe` and `pylabnet_proxy.exe`, but could not find them. My `PATH` variable also doesn't show any reference to these two files.
> 
> Should only exist for vanilla `pip install pylabnet` but not `python setup.py develop --exclude-scripts`. I can change this, but one thing that's a bit untidy is that for some reason the .exe is not removed when you use `pip uninstall pylabnet` for developer mode

I've only checked it for the `pip install pylabnet` and couldn't find it. 

ok interesting... it might be an issue with the virtual environment. it definitely worked on my machine *without* a virtual environment, i'll double check this

**Comment by mkbhaskar** [comment]
> I have tried to replicate the test strategy for developers:

1. Make new env, activate env, run `python setup.py develop --exclude-scripts /path/to/another/new/virtual/testenv/Scripts/activate`

Now, if I run `import pylabnet` from the root directory of the pylabnet folder, it works, but trying to import `pylabnet` from any other location, say from one of the demo notebooks, the import fails. This is how my `pip list` entry for `pylabnet` looks like:
image
 
` 

ok i'll look into it. my guess is all these problems are related to virtual environments, although it works on my machine so i'll need to work a bit harder to replicate your issue

**Comment by mkbhaskar** [comment]
@cknaut does launching via the .cmd scripts work?

**Comment by mkbhaskar** [comment]
> > > > I have tried to search for `pylabnet.exe` and `pylabnet_proxy.exe`, but could not find them. My `PATH` variable also doesn't show any reference to these two files.
> 
> Should only exist for vanilla `pip install pylabnet` but not `python setup.py develop --exclude-scripts`. I can change this, but one thing that's a bit untidy is that for some reason the .exe is not removed when you use `pip uninstall pylabnet` for developer mode

I've only checked it for the `pip install pylabnet` and couldn't find it. 

ok interesting... it might be an issue with the virtual environment. it definitely worked on my machine *without* a virtual environment, i'll double check this 

-----

OK, i can't reproduce this issue straightforwardly... we may have to do a walkthrough together. My steps:

1. Create a virtual environment with the command
```bash
python -m evenv C:\Users\Yogi\test_env_2
```
2. Acctivate the environment in the current shell:
```bash
C:\Users\Yogi\test_env_2\Scripts\activate
```
3. Move away from any directory with a pylabnet subdirectory (this could cause issues when calling `pip install pylabnet`. For me, this was done with `cd ..` from my home directory
4. Run `pip install pylabnet`
5. Search in windows start `pylabnet.exe` .... launch...

**Comment by mkbhaskar** [comment]
> > I have tried to replicate the test strategy for developers:

1. Make new env, activate env, run `python setup.py develop --exclude-scripts /path/to/another/new/virtual/testenv/Scripts/activate`

Now, if I run `import pylabnet` from the root directory of the pylabnet folder, it works, but trying to import `pylabnet` from any other location, say from one of the demo notebooks, the import fails. This is how my `pip list` entry for `pylabnet` looks like:
image
 
` 

ok i'll look into it. my guess is all these problems are related to virtual environments, although it works on my machine so i'll need to work a bit harder to replicate your issue 

--------------

From what working directory did you run this command? The path next to pylabnet should be the actual path to pylabnet itself, (usually `C:\users\username\pylabnet`), not to your test-environment

**Comment by cknaut** [comment]
>From what working directory did you run this command? The path next to pylabnet should be the actual path to pylabnet itself, (usually C:\users\username\pylabnet), not to your test-environment

I'm setting up the venv in a folder on my desktop, and also copy the pylabnet folder into this folder. Does the packaging assume that the `pylabnet` folder sits in the usual `C:\users\username\pylabnet` spot?

I'm trying to replicate the `pip install` steps above, this time by setting up the venv in  `C:\users\username\pylabnet`.

**Comment by mkbhaskar** [comment]
> >From what working directory did you run this command? The path next to pylabnet should be the actual path to pylabnet itself, (usually C:\users\username\pylabnet), not to your test-environment

I'm setting up the venv in a folder on my desktop, and also copy the pylabnet folder into this folder. Does the packaging assume that the `pylabnet` folder sits in the usual `C:\users\username\pylabnet` spot?

I'm trying to replicate the `pip install` steps above, this time by setting up the venv in  `C:\users\username\pylabnet`. 

-----

No, it shouldn't depend on the exact path. BUT I never put the actual pylabnet files *inside* the virtual environment directory. Maybe that's the root of the problem? Although I would have hoped it would work anyways...

**Comment by cknaut** [comment]
> > > > > I have tried to search for `pylabnet.exe` and `pylabnet_proxy.exe`, but could not find them. My `PATH` variable also doesn't show any reference to these two files.
> > 
> > 
> > Should only exist for vanilla `pip install pylabnet` but not `python setup.py develop --exclude-scripts`. I can change this, but one thing that's a bit untidy is that for some reason the .exe is not removed when you use `pip uninstall pylabnet` for developer mode
> 
> I've only checked it for the `pip install pylabnet` and couldn't find it.
> 
> ok interesting... it might be an issue with the virtual environment. it definitely worked on my machine _without_ a virtual environment, i'll double check this
> 
> OK, i can't reproduce this issue straightforwardly... we may have to do a walkthrough together. My steps:
> 
> 1. Create a virtual environment with the command
> 
> ```shell
> python -m evenv C:\Users\Yogi\test_env_2
> ```
> 
> 1. Acctivate the environment in the current shell:
> 
> ```shell
> C:\Users\Yogi\test_env_2\Scripts\activate
> ```
> 
> 1. Move away from any directory with a pylabnet subdirectory (this could cause issues when calling `pip install pylabnet`. For me, this was done with `cd ..` from my home directory
> 2. Run `pip install pylabnet`
> 3. Search in windows start `pylabnet.exe` .... launch...

This works now!

**Comment by cknaut** [comment]
> > > From what working directory did you run this command? The path next to pylabnet should be the actual path to pylabnet itself, (usually C:\users\username\pylabnet), not to your test-environment
> 
> I'm setting up the venv in a folder on my desktop, and also copy the pylabnet folder into this folder. Does the packaging assume that the `pylabnet` folder sits in the usual `C:\users\username\pylabnet` spot?
> 
> I'm trying to replicate the `pip install` steps above, this time by setting up the venv in `C:\users\username\pylabnet`.
> 
> No, it shouldn't depend on the exact path. BUT I never put the actual pylabnet files _inside_ the virtual environment directory. Maybe that's the root of the problem? Although I would have hoped it would work anyways...

A `pip install` within a vevn will put all the files in the `venv/Lib/site-packages/pylabnet` folder, so it should not be a problem having the `pylabnet` files in the venv folder.

**Comment by mkbhaskar** [comment]
>> > > > > > I have tried to search for `pylabnet.exe` and `pylabnet_proxy.exe`, but could not find them. My `PATH` variable also doesn't show any reference to these two files.
>> > 
>> > 
>> > Should only exist for vanilla `pip install pylabnet` but not `python setup.py develop --exclude-scripts`. I can change this, but one thing that's a bit untidy is that for some reason the .exe is not removed when you use `pip uninstall pylabnet` for developer mode
>> 
>> I've only checked it for the `pip install pylabnet` and couldn't find it.
>> 
>> ok interesting... it might be an issue with the virtual environment. it definitely worked on my machine _without_ a virtual environment, i'll double check this
>> 
>> OK, i can't reproduce this issue straightforwardly... we may have to do a walkthrough together. My steps:
>> 
>> 1. Create a virtual environment with the command
>> 
>> ```shell
>> python -m evenv C:\Users\Yogi\test_env_2
>> ```
>> 
> 1. Acctivate the environment in the current shell:
>> 
>> ```shell
>> C:\Users\Yogi\test_env_2\Scripts\activate
>> ```
>>
>> 1. Move away from any directory with a pylabnet subdirectory (this could cause issues when calling `pip install pylabnet`. For me, this was done with `cd ..` from my home directory
>> 2. Run `pip install pylabnet`
>> 3. Search in windows start `pylabnet.exe` .... launch...

> This works now! 

Great! We should add documentation to clarify this, although it's a bit strange for one to use `pip install pylabnet` if they have the source code. So maybe the way to separate is not `user` and `developer` but rather `pip` installation and `source` installation.. not sure

**Comment by mkbhaskar** [comment]
> > > From what working directory did you run this command? The path next to pylabnet should be the actual path to pylabnet itself, (usually C:\users\username\pylabnet), not to your test-environment
> > 
> > I'm setting up the venv in a folder on my desktop, and also copy the pylabnet folder into this folder. Does the packaging assume that the `pylabnet` folder sits in the usual `C:\users\username\pylabnet` spot?
> >
> > I'm trying to replicate the `pip install` steps above, this time by setting up the venv in `C:\users\username\pylabnet`.
> >
> > No, it shouldn't depend on the exact path. BUT I never put the actual pylabnet files _inside_ the virtual environment directory. Maybe that's the root of the problem? Although I would have hoped it would work anyways...
>
> A `pip install` within a vevn will put all the files in the `venv/Lib/site-packages/pylabnet` folder, so it should not be a problem having the `pylabnet` files in the venv folder. 

Hmm, then I'm at a loss. It does work for me, I can access `import pylabnet` statements from any directory. Can you check `/path/to/venv/Lib/site-packages/` if you have a pylabnet.egg-link file for the developer install?

**Comment by cknaut** [comment]
Yes, the pylabnet.egg-link is there. I think I have narrowed the problem down to a jupyter notebook problem.  My directory structure is :

` C:\Users\Can Knaut\testenv_3`: Location of env
`C:\Users\Can Knaut\pylabnet-packaging`: Location of pylabnet folder
Content of `pylabnet.egg-link` is  `C:\Users\Can Knaut\pylabnet-packaging`

Now, with `testenv_3` activated, I navigate to a demo folder, say `C:\Users\Can Knaut\pylabnet-packaging\demo\spectrum_analyser`. In the terminal, with  `testenv_3` activated, I can run `python; import pylabnet` successfully. Starting `jupyter notebook` in the same terminal, and then running `import pylabnet` in a notebook cell fails.

**Comment by mkbhaskar** [comment]
>  I think I have narrowed the problem down to a jupyter notebook problem.

You're right - I didn't test Jupyter notebooks. It doesn't work :(

I'll look into it, but I'm not sure what the issue is immediately. Running 
```bash
python -i
```
And using an interactive python session in the terminal works fine.

**Comment by mkbhaskar** [comment]
Do we need to do something like this: https://janakiev.com/blog/jupyter-virtual-envs/

**Comment by cknaut** [comment]
Interestingly, the notebooks work for `pip` installation (maybe cross check this).

**Comment by mkbhaskar** [comment]
> Interestingly, the notebooks work for `pip` installation (maybe cross check this).  

you're absolutely right. If you check `sys.executable`, it uses the base conda executable in the developer mode, but the virtual environment executable in `pip install` mode. 

Let me look into this, there's something funny going on with the developer mode, maybe it's in the documentation of `setuptools`. I'll get back to you.

**Comment by cknaut** [comment]
> Do we need to do something like this: https://janakiev.com/blog/jupyter-virtual-envs/

Tried this, cannot activate the newly created kernel.

**Comment by mkbhaskar** [comment]
realized something interesting. there is no `jupyter-notebook.exe` in the /path/to/venv/Scripts directory, whereas this exists when you use the ordinary `pip install`. I'm confident this is at the root of the problem, but I haven't been able to find out where this arises from

**Comment by mkbhaskar** [comment]
added support for jupyter notebooks in f73d26f. `pip install jupyter` must be run before `setuptools.setup(**kwargs)`. Didn't manage to figure out why this is.. but it seems like a harmless fix.

the only downside is that the `python setup.py develop` command will throw some useless errors, since it first tries to install pylabnet without dependencies (since there is a `setup.py` file in the cwd), then fails and proceeds to install `jupyter`, then evaluates `setuptools.setup()` within `setup.py`.

> **_IMPORTANT NOTE:_** you need to completely wipe your virtual environment and start over if it was installed in the preivous way, since jupyter will not be properly re-installed otherwise. Or just use a brand new virtual environment.

**Comment by cknaut** [comment]
Tried installing it, getting the following error regarding the venv path argument:
image


Replacing the backslashes by `/` or `\` doesn't work either. Can you spot a mistake?

Alternatively, have you tried using pip installing the `setup.py` file directly? This can be done by calling `pip install .` inside the directory of `setup.py`. I gave it a try and jupyter notebooks seem to work. But of course then you would note get the automatic modification of the `.cmd` files....

**Comment by mkbhaskar** [comment]
> Alternatively, have you tried using pip installing the setup.py file directly? This can be done by calling pip install . inside the directory of setup.py. I gave it a try and jupyter notebooks seem to work. But of course then you would note get the automatic modification of the .cmd files....

That doesn't work for development, unless you want to pip install *each time* you are testing your code. you need to use python setup.py develop to create the "linked" install which just links the `import pylabnet` calls to the codebase where you run the `setup.py` from, so it can be edited and tested

**Comment by mkbhaskar** [comment]
There was a bug in `setup.py` which was fixed in ece4ae3. It should work now

**Comment by mkbhaskar** [comment]
@cknaut, we no longer need to use `.cmd` launching. i have the `.exe` launching working with developer mode now (at least on my machine). can you test it?

**Comment by cknaut** [comment]
> That doesn't work for development, unless you want to pip install _each time_ you are testing your code. you need to use python setup.py develop to create the "linked" install which just links the `import pylabnet` calls to the codebase where you run the `setup.py` from, so it can be edited and tested

Makes sense!

**Pull request merged**
