### PR TITLE
Issue #246: add lab names to clients

### PR DESCRIPTION
**Pull request by pieterjanstas**
This pull request adds lab names to client data when the server is launched:
Screenshot 2022-01-12 at 15 20 06
The way this is done is by adding a lab_name.json config file with following layout:
Screenshot 2022-01-12 at 14 45 07
If the file does not exist, it will be assigned the lab name: 'NO LAB'
The launch control GUI can filter by lab:
Screenshot 2022-01-12 at 13 29 48
Screenshot 2022-01-12 at 13 29 56
The lab name is compatible with client searching, i.e. you can filter by name and lab name at the same time.

Extra: command length shown even if it is too long, which can be helpful for debugging:
Screenshot 2022-01-12 at 15 14 44

### CODE REVIEW

**Comment by pieterjanstas** [comment]
UPDATE: lab name is now added in device and script config files:
image

Now three lab name options: B16, G12, SHARED. If no lab name is specified --> automatically NO_LAB added as lab name.

lab_name.json file still used to set lab name of logger_GUI

Bug: sometimes when new server gets instantiated, it is missing port, lab_name. This is a separate issue and needs to be resolved

**Comment by pieterjanstas** [comment]
Also: if lab_name.json does not exist, --> NO_LAB name given

**Comment by cknaut** [comment]
This PR also includes the `current_g12_experiment` branch, as well as fixes for #307. To fix #307, a launched script now queries the device list via a newly generated `log.get_client_dict()` function, making it superfluous to pass all clients via the command line.

**Review by cknaut — APPROVED** [review]
lgto, @huanyanqi , can you have a quick look?

**Review by huanyanqi — APPROVED** [review]

**Pull request merged**
