### PR TITLE
logger-dev

### PR DESCRIPTION
**Pull request by mkbhaskar**
#  New feature: Convenient software launching

The main concept is that we can now place scripts in the launchers directory, and by launching them from `Launch Control`, they know exactly what servers are running, and can also instantiate (or simply connect to active) servers to run their functinoality.

For ultimate convenience, a pylabnet.cmd file has been placed in the base directory which should enable simple double-click launching of the main GUI from which other scripts in the launcher directory can be launched.

## Using the feature

1. Make sure your Windows default `python` executable runs from the pylabnet environment. You can do this by modifying the `PATH` variable so that the path to the pylabnet python.exe is *before* any other paths that contain another python.exe file
2. Modify the shortcut with the device icon in the main pylabnet directory
    1. Copy the shortcut to your desktop.
    2. Right-click on the shortcut, and select properties
    3. In the "Start in" field, replace whatever is entered with the local machine's path to the pylabnet/launchers/ directory. This should be already listed in the "Target" field. *Still trying to come up with a more elegant way to do this, but this is simplest for now*
3. Double-click your new desktop shortcut. This should launch a minimzied shell and the pylabnet `Launch Control` GUI.
4. From here, you can 
    1. Run any scripts in the pylabnet/launcher directory by double clicking on the desired script
    2. View all active clients to the running `Logger`
    3. View all client information, including port number (if the client is running its own server) and .ui file (if the client is a GUI)
5. In addition to experimental scripts, you can launch:
    1. An arbitrary GUI using the `pylabnet_GUI` script, which will prompt you to choose a ui template from the command line
    2. An arbitrary module which contains an appropriate `launch(**kwargs)` method using the `pylabnet_server` script

## Developing within the new framework

1. Add your top-level launching script to the pylabnet/launchers directory. For an example of this script, see counters.py
    1. The launching script (in the example case, counters.py) should instantiate a `Launcher` object defined in launcher.py
    2. During instantiation, pass the `Launcher` all information required to run the desired application. This includes:
        1. **A list of script modules to execute, sequentially (e.g. `[script_module]`).**
            * This module can implement arbitrary classes, but the module itself must have a method `script_module.launcher(**kwargs)` which can run the desired script/application (see `count_monitor.launcher(**kwargs)` for an example and/or `Launcher._launch_scripts()` for the generic implementation)
            * These will be run in the main process thread, and in general require other servers and/or GUIs to be running (see below)
            * In our counter example, we want to run a single script given in the monitor_counts.py module. 
        2. **A list of required server modules to be running, prior to execution of the script(s) (e.g. `[server_module_1, server_module_2]`).**
            * These modules should be imported at the top of the launcher script file (in the example case, counter.py)
            * Each server module should have a `server_module.launch(**kwargs)` method that performs connection to hardware (if necessary) and instantiates the desired server
            * Parameters are *not* passed to individual server modules, so any specific configurations should be specified directly in the definition of `server_module.launch(**kwargs)`. *We can consider passing parameters when programming the launcher script, but in reality once configured initially, the hardware + server instantiation should be relatively static, with all variable input happening via the client.*
            * These servers are instantiated in a separate process using `subprocess.Popen` to run the pylabnet_server.py script
            * Once a server is instantiated, a `test_module.Client` will be instantiated in the main launcher thread
            * This client will be passed as part of `**kwargs` to each of the scripts, so that the script has access to all necessary clients
        3. **A list of required GUI modules to be running.** The logic is very similar to item (2) above, but in this case one just needs to provide a list of .ui files, and the necessary GUI servers will be launched in separate processes, with corresponding clients instantiated in the main thread to be passed to the experimental scripts
        4. **A list of parameter dictionaries for each script**, to enable passing arbitrary parameters to each script via `kwargs['params']` in the scripts `launcher(**kwargs)` function (see `count_monitor.launcher(**kwargs)` for an example)
    3. Call Launcher.launch(). That's it.
2. Make sure pylabnet_server.py imports all of the server modules your script(s) require, since this will be the script used to launch them. *We can potentially come up with a better way of doing this, perhaps by consolidating dedicated server launching scripts in a unique location.*
3. Now you should be able to launch your script and requisite servers with a simple double-click from the Launch Control!
4. In practice, everything may fail, and it may seem to be difficult to trace what is happening. In order to debug scripts that you are launching via `Launch Control`:
    1. Place a `time.sleep(x)` statement at the top of your script.
    2. Attach a debugger to the active process launched by the double-click before it executes beyond the `sleep(x)` statement 
    (make sure there is a suitable breakpoint in place)
        *In Visual Studio, this requires configuring a debugger with a launch.json file that looks like this:
        ```
        {
            "name": "Python: attach to launcher",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
        ```
        * Launch the process (with double-click), then launch the debugger immediately following
        * It will give you a search bar to search for and select the process to debug
    3. Now you can debug your subprocess that was launched via Launch Control!
    4. Each time you encounter an instantiation of Popen(), this will launch a new process that will need to be separately debugged. *Note that you **can** have multiple debuggers running simultaneously, you just need to make multiple configurations in your launch.json file that have different `"name"` subfields. So you can play the same trick over and over again to your heart's desire.*

### CODE REVIEW

**Comment by cknaut** [comment]
I am starting to test this out now and am working on setting the `PATH` variable correctly. Maybe there is another way to start the `.cmd` file using the `pylabnet` environment? I might not understand this correctly, but it seems a bit invasive to force to user to use the `pylabnet` environment as default python environment.

**Comment by mkbhaskar** [comment]
yeah, i agree. i didn't find a way to do generically access the correct executable from the commandline, but i can try a bit harder. for now, to test things, you can just run "PATHTOPYLABNETEXECUTABLE/python.exe launch_control.py" to test things. 

if that doesn't work.... then just stop for now and i'll look into it more

**Comment by mkbhaskar** [comment]
here's an idea: how about having the user create a new environment variable to store the path "e.g. PYLABNETPATH"? then we should be able to access it from cmd. This can be part of standard setup, it's not more work than the current setup procedure

Let me know what you think and I can make the minor modification to the .cmd file

**Comment by cknaut** [comment]
That could be an idea! Alternatively, how about adding the `conda activate pylabnet` command to the .cmd file?

**Comment by mkbhaskar** [comment]
oh, duh. i'm so used to avoiding windows cmd in real life, i forgot that was standard operating procedure :)

**Comment by mkbhaskar** [comment]
should be fixed now with https://github.com/lukingroup/pylabnet/pull/28/commits/8f9807ae77d631462bef1b9558ea8bc35a808d77

**Comment by cknaut** [comment]
Awesome, works like a charm now!

**Comment by cknaut** [comment]
I have also modified the bash command for opening new scripts to include the `activate` statement:

image


Do you see any problem with that?

**Comment by mkbhaskar** [comment]
yeah, i think there's actually a more elegant way of doing it: 
```python
        # Build the bash command to input all active servers and relevant port numbers to script
        bash_cmd = 'start /min "{}, {}" /wait {} {} --logport {} --numclients {}'.format(
            script_to_run, 
            launch_time,
            sys.executable,
            os.path.join(os.path.dirname(os.path.realpath(__file__)),script_to_run), 
            self.log_port, 
            len(self.client_list)
        )
```
Where `sys.executable` uses the same executable used to instantiate the currently running python script. I think all the scripts should be called in this way, I meant to implement it like that but I guess I forgot

**Comment by cknaut** [comment]
No, it was actually implemented like this and I changed it because I though it was necessary due to the `activate` call. Reverted it back and it works!

**Comment by cknaut** [comment]
Regarding the debugging workflow: Maybe the time delay needed to attach to the debugger can be implemented in a convenient way: We could add a tickbox on the Launch control, which when ticked calls the launching script with a flag like `python wavemeter.py --debug`, which then in turn creates a variable beeing passed into the launcher such as:

```python

# variable debug retrieved from command line
launcher.launch(debug=debug)

...

# in launcher.launch:

def launch(debug):
    if debug:
        time.sleep(30)
```

**Comment by cknaut** [comment]
Adding to the last comment, I think I found a way to replace the `sleep` statment:

Using

```python
import ptvsd
# 5678 is the default attach port in the VS Code debug configurations
print("Waiting for debugger attach")
ptvsd.enable_attach(address=('localhost', 5678))
ptvsd.wait_for_attach()
breakpoint()
```
in the script that is launched remotely and having a debug config setting as follows:

```json
{
            "name": "Python: attach to launcher",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "redirectOutput" : true,
            "processId": "${command:pickProcess}"
}
```

Will yield the desired effect: The code execution is halted until a debugger is attached.

Combining this with the comment above might be worth exploring. Let's discuss.

**Comment by mkbhaskar** [comment]
Cool, that looks very promising - I like it! This hostname/port is completely unrelated to the actual pylabnet server running in the script, right?

If that works nicely, I recommend to just make a short helper method so that we can just add a single line `pylabnet_debugger(enable=True)` or something at the top of our code in order to debug

**Comment by cknaut** [comment]
No, the port-number is referring to the same ones as in `rpyc`, meaning that if a debugger is attached to a process using number `5678`, this port is no longer available. I think this would also be the case if we were to use the sleep statement. We could hardcode this port number to be excluded in the random port number generation to avoid conflicts.

**Comment by cknaut** [comment]
I finished implementing a simple gui toogling a `StaticLine` via an NIDAQmx, and it works great. I made some commits which boiled down to:

- Changing some driver names to `Driver()` and making sure the `staticline.Driver()` class works with the new nomenclature (uniform `Driver()` names)
- Encapsulating the python and module shell commands by `" "`, such that path names with spaces don't fail. Unfortunately, Windows auto-assigns your home folder to your name, such that spaces in filepaths such as `C:\Users\Firstname Lastname\...` are common and unavoidable :(
- Adding the script, hardware and script `launch()` methods, the `.ui` file and the launcher to make the example gui `staticline_gui_test` work.

I'll let you review the commits and then merge. I like the launcher a lot and have some general remarks:


1. Debugging is key, given the increased complexity and multi-threaded-ness. I think it's worth implementing and testing a user-friendly debugging infrastructure, possible with the elements mentioned above. 
2.  I have a bit troubles with the `launch` scripts in the hardware modules. I agree with you that once a configuration is set, it's unlikely to change, but I don't think the hardware module is the place where and hardware instantiation should take place. Maybe we can write some helper class which facilitates hardware instantiation?
3. Related to point 2.: Is there a way to define a GUI which uses two instances of the same class? This could be relevant for example if we use multiple instances of staticlines. It seems that the name-based instantiation could not immediately allow for the instantiation of the same class.
4. Minor point: Is there a possibility to hide all console windows which are not used?
5. Minor point: If I close my GUI window after having started it using the double-click on the script name, I can't seem to re-start it be double-clicking on the script name a second time. Is this the expected behavior?

**Comment by mkbhaskar** [comment]
> No, the port-number is referring to the same ones as in `rpyc`, meaning that if a debugger is attached to a process using number `5678`, this port is no longer available. I think this would also be the case if we were to use the sleep statement. We could hardcode this port number to be excluded in the random port number generation to avoid conflicts.  

OK, this makes sense and is fine with me. I may update the auto-connection parameters in the future, and this is a natural issue to deal with in the network  branch

**Comment by mkbhaskar** [comment]
> I finished implementing a simple gui toogling a `StaticLine` via an NIDAQmx, and it works great. I made some commits which boiled down to:

- Changing some driver names to `Driver()` and making sure the `staticline.Driver()` class works with the new nomenclature (uniform `Driver()` names)
- Encapsulating the python and module shell commands by `" "`, such that path names with spaces don't fail. Unfortunately, Windows auto-assigns your home folder to your name, such that spaces in filepaths such as `C:\Users\Firstname Lastname\...` are common and unavoidable :(
- Adding the script, hardware and script `launch()` methods, the `.ui` file and the launcher to make the example gui `staticline_gui_test` work.

I'll let you review the commits and then merge. I like the launcher a lot and have some general remarks:


1. Debugging is key, given the increased complexity and multi-threaded-ness. I think it's worth implementing and testing a user-friendly debugging infrastructure, possible with the elements mentioned above. 
2.  I have a bit troubles with the `launch` scripts in the hardware modules. I agree with you that once a configuration is set, it's unlikely to change, but I don't think the hardware module is the place where and hardware instantiation should take place. Maybe we can write some helper class which facilitates hardware instantiation?
3. Related to point 2.: Is there a way to define a GUI which uses two instances of the same class? This could be relevant for example if we use multiple instances of staticlines. It seems that the name-based instantiation could not immediately allow for the instantiation of the same class.
4. Minor point: Is there a possibility to hide all console windows which are not used?
5. Minor point: If I close my GUI window after having started it using the double-click on the script name, I can't seem to re-start it be double-clicking on the script name a second time. Is this the expected behavior?

 

- (1) Yes, I agree, I like your suggestions, and I added issue #31 for this
- (2) I agree, I'm not quite happy with this (issue #32 raised). I may implement a separate sub-module for hardware instantiation to keep it modular. This will also help with the issue of "making sure pylabnet_server.py imports your module" since then we can just have it import all modules within the specific server instantiation sub-module.
- (3) It is absolutely possible, but one then needs to configure the launcher not to auto-connect to the running GUI. It may be worth demoting the auto-connect feature and actually have the launcher prompt the user for permission to auto-connect
- (4) I implemented auto-minimization, but I actually don't know how to close open threads (instantiated servers) unless you have access to the console window. E.g. if you open a GUI, close the GUI, but have the console hidden, the python process containing the GUI server lives on and must be terminated in task manager... If you have ideas, please let me know
- (5) See point 4. The GUI server lives on if you only close the window. Although it should be possible to instantiate multiple instances of the GUI.

Regarding points 4 and 5 - I didn't look deeply into `server.kill()` techniques. I have raised an issue (#30) on this.

**Pull request merged**
